"""Train the General ISL INCLUDE-50 motion-aware baseline.

This trainer consumes the sequence files generated by
``prepare_include50_sequences.py``. It deliberately preserves the official
AI4Bharat INCLUDE train/validation/test splits and keeps this General ISL V4
model separate from the working Emergency ISL V3 model.

The INCLUDE metadata used by this project does not expose verified signer
identities. Consequently, this script reports an official-split evaluation,
not a signer-disjoint evaluation.
"""

import csv
from collections import Counter
from pathlib import Path

import joblib
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
)


# =========================================================
# Configuration
# =========================================================

PROJECT_ROOT = Path(__file__).resolve().parent

MANIFEST_PATH = (
    PROJECT_ROOT
    / "data"
    / "sequences_include50_v4"
    / "manifest.csv"
)

MODEL_PATH = (
    PROJECT_ROOT
    / "models"
    / "gesture_sequence_include50_v4.joblib"
)

SEQUENCE_LENGTH = 48
FRAME_FEATURE_COUNT = 132
KEYFRAME_COUNT = 8
MIN_DETECTION_RATIO = 0.30
RANDOM_STATE = 42
ALLOWED_SPLITS = ("train", "val", "test")
READY_STATUS = "READY"


# =========================================================
# Convert a sequence into motion-aware model features
# =========================================================

def sequence_to_model_features(sequence):
    """Convert one (48, 132) sequence into a fixed feature vector.

    This is intentionally identical to the transformation used by the
    Emergency ISL V3 baseline:

    - Eight ordered keyframes
    - Mean, standard deviation, minimum and maximum
    - First frame, last frame and overall displacement
    - Velocity statistics
    - Acceleration statistics
    """

    sequence = np.asarray(sequence, dtype=np.float32)

    expected_shape = (
        SEQUENCE_LENGTH,
        FRAME_FEATURE_COUNT,
    )

    if sequence.shape != expected_shape:
        raise ValueError(
            f"Expected {expected_shape}, received "
            f"{sequence.shape}"
        )

    if not np.isfinite(sequence).all():
        raise ValueError(
            "Sequence contains NaN or infinite values."
        )

    keyframe_indices = np.rint(
        np.linspace(
            0,
            SEQUENCE_LENGTH - 1,
            KEYFRAME_COUNT,
        )
    ).astype(int)

    keyframes = sequence[keyframe_indices].reshape(-1)

    sequence_mean = np.mean(sequence, axis=0)
    sequence_std = np.std(sequence, axis=0)
    sequence_min = np.min(sequence, axis=0)
    sequence_max = np.max(sequence, axis=0)

    first_frame = sequence[0]
    last_frame = sequence[-1]
    displacement = last_frame - first_frame

    velocity = np.diff(sequence, axis=0)

    velocity_mean = np.mean(velocity, axis=0)
    velocity_mean_absolute = np.mean(
        np.abs(velocity),
        axis=0,
    )
    velocity_std = np.std(velocity, axis=0)
    velocity_max_absolute = np.max(
        np.abs(velocity),
        axis=0,
    )

    acceleration = np.diff(velocity, axis=0)

    acceleration_mean_absolute = np.mean(
        np.abs(acceleration),
        axis=0,
    )
    acceleration_std = np.std(
        acceleration,
        axis=0,
    )
    acceleration_max_absolute = np.max(
        np.abs(acceleration),
        axis=0,
    )

    model_features = np.concatenate(
        [
            keyframes,
            sequence_mean,
            sequence_std,
            sequence_min,
            sequence_max,
            first_frame,
            last_frame,
            displacement,
            velocity_mean,
            velocity_mean_absolute,
            velocity_std,
            velocity_max_absolute,
            acceleration_mean_absolute,
            acceleration_std,
            acceleration_max_absolute,
        ]
    ).astype(np.float32)

    if not np.isfinite(model_features).all():
        raise ValueError(
            "Transformed features contain invalid values."
        )

    return model_features


# =========================================================
# Manifest and sequence loading
# =========================================================

def resolve_project_path(path_text):
    """Resolve manifest paths written relative to the project root."""

    path = Path(path_text)

    if path.is_absolute():
        return path

    return PROJECT_ROOT / path


def load_dataset():
    """Load READY sequences while preserving official split membership."""

    if not MANIFEST_PATH.exists():
        raise FileNotFoundError(
            f"Manifest not found:\n{MANIFEST_PATH}"
        )

    features_by_split = {
        split: []
        for split in ALLOWED_SPLITS
    }

    labels_by_split = {
        split: []
        for split in ALLOWED_SPLITS
    }

    paths_by_split = {
        split: []
        for split in ALLOWED_SPLITS
    }

    status_counts = Counter()
    invalid_rows = 0
    seen_sequence_paths = set()
    model_feature_count = None

    with MANIFEST_PATH.open(
        "r",
        newline="",
        encoding="utf-8",
    ) as file:
        reader = csv.DictReader(file)

        required_fields = {
            "sequence_path",
            "split",
            "label",
            "status",
            "detection_ratio",
        }

        missing_fields = required_fields.difference(
            reader.fieldnames or []
        )

        if missing_fields:
            raise ValueError(
                "Manifest is missing required columns: "
                f"{sorted(missing_fields)}"
            )

        for row_number, row in enumerate(
            reader,
            start=2,
        ):
            status = row["status"].strip().upper()
            status_counts[status or "BLANK"] += 1

            if status != READY_STATUS:
                continue

            split = row["split"].strip().lower()
            label = row["label"].strip().upper()

            if split not in ALLOWED_SPLITS:
                print(
                    f"WARNING: Row {row_number} has "
                    f"unsupported split {split!r}."
                )
                invalid_rows += 1
                continue

            if not label:
                print(
                    f"WARNING: Row {row_number} has no label."
                )
                invalid_rows += 1
                continue

            try:
                detection_ratio = float(
                    row["detection_ratio"]
                )
            except (TypeError, ValueError):
                print(
                    f"WARNING: Row {row_number} has an "
                    "invalid detection ratio."
                )
                invalid_rows += 1
                continue

            if detection_ratio < MIN_DETECTION_RATIO:
                print(
                    f"WARNING: READY row {row_number} is "
                    "below the minimum detection ratio."
                )
                invalid_rows += 1
                continue

            sequence_path = resolve_project_path(
                row["sequence_path"]
            )

            canonical_path = str(
                sequence_path.resolve()
            ).casefold()

            if canonical_path in seen_sequence_paths:
                print(
                    f"WARNING: Duplicate sequence ignored: "
                    f"{sequence_path}"
                )
                invalid_rows += 1
                continue

            if not sequence_path.exists():
                print(
                    f"WARNING: Missing sequence: "
                    f"{sequence_path}"
                )
                invalid_rows += 1
                continue

            try:
                with np.load(
                    sequence_path,
                    allow_pickle=False,
                ) as data:
                    sequence = np.asarray(
                        data["sequence"],
                        dtype=np.float32,
                    )

                    if "label" in data.files:
                        stored_label = str(
                            data["label"].item()
                        ).strip().upper()

                        if stored_label != label:
                            raise ValueError(
                                "NPZ label does not match the "
                                f"manifest ({stored_label!r} "
                                f"!= {label!r})."
                            )

                    if "split" in data.files:
                        stored_split = str(
                            data["split"].item()
                        ).strip().lower()

                        if stored_split != split:
                            raise ValueError(
                                "NPZ split does not match the "
                                f"manifest ({stored_split!r} "
                                f"!= {split!r})."
                            )

                features = sequence_to_model_features(
                    sequence
                )

            except Exception as error:
                print(
                    f"WARNING: Could not load "
                    f"{sequence_path.name}: {error}"
                )
                invalid_rows += 1
                continue

            if model_feature_count is None:
                model_feature_count = len(features)
            elif len(features) != model_feature_count:
                print(
                    f"WARNING: Inconsistent feature count in "
                    f"{sequence_path.name}."
                )
                invalid_rows += 1
                continue

            seen_sequence_paths.add(canonical_path)
            features_by_split[split].append(features)
            labels_by_split[split].append(label)
            paths_by_split[split].append(
                str(sequence_path.resolve())
            )

    if model_feature_count is None:
        raise ValueError(
            "No valid READY sequences were found."
        )

    datasets = {}

    for split in ALLOWED_SPLITS:
        split_features = features_by_split[split]

        if split_features:
            X = np.asarray(
                split_features,
                dtype=np.float32,
            )
        else:
            X = np.empty(
                (0, model_feature_count),
                dtype=np.float32,
            )

        y = np.asarray(labels_by_split[split])

        datasets[split] = {
            "X": X,
            "y": y,
            "paths": paths_by_split[split],
        }

    return (
        datasets,
        status_counts,
        invalid_rows,
        model_feature_count,
    )


# =========================================================
# Dataset checks and reporting
# =========================================================

def print_label_counts(split, labels, label_order):
    counts = Counter(labels)

    print(f"\n{split.upper()} sequences per label:")

    for label in label_order:
        print(f"  {label}: {counts[label]}")


def validate_official_splits(datasets):
    """Check that official splits are disjoint and suitable for training."""

    for split in ALLOWED_SPLITS:
        if len(datasets[split]["X"]) == 0:
            raise RuntimeError(
                f"Official {split!r} split has no usable "
                "sequences."
            )

    path_sets = {
        split: set(datasets[split]["paths"])
        for split in ALLOWED_SPLITS
    }

    for first_index, first_split in enumerate(
        ALLOWED_SPLITS
    ):
        for second_split in ALLOWED_SPLITS[
            first_index + 1:
        ]:
            overlap = path_sets[first_split].intersection(
                path_sets[second_split]
            )

            if overlap:
                raise RuntimeError(
                    "Sequence leakage detected between "
                    f"{first_split} and {second_split}: "
                    f"{sorted(overlap)[:3]}"
                )

    label_sets = {
        split: set(datasets[split]["y"])
        for split in ALLOWED_SPLITS
    }

    all_labels = sorted(
        set().union(*label_sets.values())
    )

    if len(all_labels) != 50:
        raise RuntimeError(
            "Expected 50 INCLUDE labels, found "
            f"{len(all_labels)}."
        )

    missing_train_labels = (
        set(all_labels) - label_sets["train"]
    )

    missing_test_labels = (
        set(all_labels) - label_sets["test"]
    )

    missing_val_labels = (
        set(all_labels) - label_sets["val"]
    )

    if missing_train_labels:
        raise RuntimeError(
            "Training split is missing labels: "
            f"{sorted(missing_train_labels)}"
        )

    if missing_val_labels:
        print(
            "WARNING: Validation split is missing "
            f"{len(missing_val_labels)} label(s): "
            f"{sorted(missing_val_labels)}"
        )

    if missing_test_labels:
        print(
            "WARNING: Testing split is missing "
            f"{len(missing_test_labels)} label(s) after "
            "quality filtering: "
            f"{sorted(missing_test_labels)}"
        )

    return (
        all_labels,
        sorted(label_sets["val"]),
        sorted(label_sets["test"]),
        sorted(missing_val_labels),
        sorted(missing_test_labels),
    )


# =========================================================
# Model training and evaluation
# =========================================================

def build_classifier():
    return RandomForestClassifier(
        n_estimators=500,
        random_state=RANDOM_STATE,
        class_weight="balanced_subsample",
        n_jobs=-1,
        max_features="sqrt",
    )


def evaluate_classifier(
    classifier,
    X,
    y,
    report_labels,
    split_name,
):
    predictions = classifier.predict(X)

    accuracy = accuracy_score(y, predictions)

    macro_f1 = f1_score(
        y,
        predictions,
        labels=report_labels,
        average="macro",
        zero_division=0,
    )

    print(f"\n{split_name} evaluation")
    print("-" * (len(split_name) + 11))
    print(f"Sequences: {len(X)}")
    print(f"Accuracy: {accuracy * 100:.2f}%")
    print(f"Macro F1: {macro_f1:.4f}")

    print("\nClassification report:")

    print(
        classification_report(
            y,
            predictions,
            labels=report_labels,
            digits=4,
            zero_division=0,
        )
    )

    return predictions, float(accuracy), float(macro_f1)


def print_top_confusions(
    true_labels,
    predicted_labels,
    label_order,
    limit=15,
):
    matrix = confusion_matrix(
        true_labels,
        predicted_labels,
        labels=label_order,
    )

    confusions = []

    for true_index, true_label in enumerate(
        label_order
    ):
        for predicted_index, predicted_label in enumerate(
            label_order
        ):
            if true_index == predicted_index:
                continue

            count = int(
                matrix[true_index, predicted_index]
            )

            if count:
                confusions.append(
                    (
                        count,
                        true_label,
                        predicted_label,
                    )
                )

    confusions.sort(
        key=lambda item: (
            -item[0],
            item[1],
            item[2],
        )
    )

    print("\nMost frequent test confusions:")

    if not confusions:
        print("  None")
        return matrix

    for count, true_label, predicted_label in (
        confusions[:limit]
    ):
        print(
            f"  {true_label} -> {predicted_label}: "
            f"{count}"
        )

    return matrix


# =========================================================
# Main pipeline
# =========================================================

def main():
    print("ISL INCLUDE-50 Sequence Classifier V4")
    print("-------------------------------------")
    print(f"Manifest: {MANIFEST_PATH}")
    print("Evaluation: Official train/val/test splits")
    print("Signer metadata: Unavailable")

    (
        datasets,
        status_counts,
        invalid_rows,
        model_feature_count,
    ) = load_dataset()

    (
        label_order,
        validation_label_order,
        test_label_order,
        missing_validation_labels,
        missing_test_labels,
    ) = validate_official_splits(datasets)

    train = datasets["train"]
    validation = datasets["val"]
    test = datasets["test"]

    print("\nDataset summary")
    print("---------------")
    print(f"READY manifest rows: {status_counts['READY']}")
    print(
        "LOW_DETECTION manifest rows: "
        f"{status_counts['LOW_DETECTION']}"
    )
    print(f"Invalid READY rows skipped: {invalid_rows}")
    print(f"Training sequences: {len(train['X'])}")
    print(
        f"Validation sequences: "
        f"{len(validation['X'])}"
    )
    print(f"Testing sequences: {len(test['X'])}")
    print(f"Number of labels: {len(label_order)}")
    print(f"Frames per sequence: {SEQUENCE_LENGTH}")
    print(
        f"Features per frame: {FRAME_FEATURE_COUNT}"
    )
    print(
        "Model features per sequence: "
        f"{model_feature_count}"
    )
    print("Sequence path overlap: 0")

    print_label_counts(
        "train",
        train["y"],
        label_order,
    )

    print_label_counts(
        "val",
        validation["y"],
        label_order,
    )

    print_label_counts(
        "test",
        test["y"],
        label_order,
    )

    # -----------------------------------------------------
    # Development model: train only on official train split
    # -----------------------------------------------------

    development_classifier = build_classifier()

    print(
        "\nTraining development model on the official "
        "training split..."
    )

    development_classifier.fit(
        train["X"],
        train["y"],
    )

    (
        _,
        validation_accuracy,
        validation_macro_f1,
    ) = evaluate_classifier(
        development_classifier,
        validation["X"],
        validation["y"],
        validation_label_order,
        "Validation",
    )

    # -----------------------------------------------------
    # Final model: refit on official train + validation data
    # -----------------------------------------------------

    X_final_train = np.concatenate(
        [train["X"], validation["X"]],
        axis=0,
    )

    y_final_train = np.concatenate(
        [train["y"], validation["y"]],
        axis=0,
    )

    final_classifier = build_classifier()

    print(
        "\nRefitting final model on official train + "
        "validation sequences..."
    )

    final_classifier.fit(
        X_final_train,
        y_final_train,
    )

    (
        test_predictions,
        test_accuracy,
        test_macro_f1,
    ) = evaluate_classifier(
        final_classifier,
        test["X"],
        test["y"],
        test_label_order,
        "Untouched test",
    )

    matrix = print_top_confusions(
        test["y"],
        test_predictions,
        label_order,
    )

    # -----------------------------------------------------
    # Save model and reproducibility metadata
    # -----------------------------------------------------

    MODEL_PATH.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    model_data = {
        "model": final_classifier,
        "labels": label_order,
        "sequence_length": SEQUENCE_LENGTH,
        "frame_feature_count": FRAME_FEATURE_COUNT,
        "model_feature_count": model_feature_count,
        "keyframe_count": KEYFRAME_COUNT,
        "feature_transform": "TEMPORAL_SUMMARY_V1",
        "minimum_detection_ratio": MIN_DETECTION_RATIO,
        "random_state": RANDOM_STATE,
        "split_strategy": "OFFICIAL_INCLUDE_TRAIN_VAL_TEST",
        "signer_metadata_available": False,
        "validation_evaluated_labels": validation_label_order,
        "test_evaluated_labels": test_label_order,
        "missing_validation_labels": missing_validation_labels,
        "missing_test_labels": missing_test_labels,
        "development_training_sample_count": len(
            train["X"]
        ),
        "validation_sample_count": len(
            validation["X"]
        ),
        "final_training_sample_count": len(
            X_final_train
        ),
        "testing_sample_count": len(test["X"]),
        "validation_accuracy": validation_accuracy,
        "validation_macro_f1": validation_macro_f1,
        "test_accuracy": test_accuracy,
        "test_macro_f1": test_macro_f1,
        # Compatibility with the existing live application.
        "accuracy": test_accuracy,
        "macro_f1": test_macro_f1,
        "confusion_matrix": matrix,
        "source": "AI4BHARAT_INCLUDE50",
        "dataset_id": "ai4bharat/INCLUDE",
        "ready_sequence_count": int(
            status_counts["READY"]
        ),
        "excluded_low_detection_count": int(
            status_counts["LOW_DETECTION"]
        ),
    }

    joblib.dump(
        model_data,
        MODEL_PATH,
        compress=3,
    )

    print("\nModel saved successfully at:")
    print(MODEL_PATH)

    print(
        "\nIMPORTANT: This is an official-split INCLUDE-50 "
        "baseline, not a signer-disjoint evaluation. "
        "Keep Emergency V3 as the stable demo until this "
        "model also passes live-webcam testing and UNKNOWN "
        "rejection is added."
    )


if __name__ == "__main__":
    main()